##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by dev-cetera.com & contributors. The use of this
## source code is governed by an MIT-style license described in the LICENSE
## file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_generate_screen
homepage: https://dev-cetera.com/
repository: https://github.com/robmllze/df_generate_screen
funding:
  - https://www.buymeacoffee.com/dev_cetera
  - https://www.patreon.com/c/RobertMollentze
  - https://github.com/sponsors/robmllze
description: A tool to generate ready-made screen templates for your Flutter app (uses df_sceen)
version: 0.8.1
topics:
  - source-gen
  - build-runner
  - code-generation
  - screen
  - pages

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  args: ^2.7.0
  path: ^1.9.1

  df_collection: ^0.9.8
  df_config: ^0.7.5
  df_gen_core: ^0.7.0
  df_generate_dart_indexes: ^0.6.1
  df_generate_dart_models_core: ^0.9.22
  df_log: ^0.3.19
  df_screen_core: ^0.5.5
  df_string: ^0.2.9
  df_type: ^0.14.2

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
  

## -----------------------------------------------------------------------------

executables:
  --screen: df_generate_screen
  --access: df_generate_screen_access
  --bindings: df_generate_screen_bindings
  df_generate_screen: df_generate_screen
  df_generate_screen_access: df_generate_screen_access
  df_generate_screen_bindings: df_generate_screen_bindings

