##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by dev-cetera.com & contributors. The use of this
## source code is governed by an MIT-style license described in the LICENSE
## file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_generate_screen
description: A tool to generate ready-made screen templates for your Flutter app (uses df_sceen)
version: 0.6.6
homepage: https://dev-cetera.com
repository: https://github.com/dev-cetera/df_generate_screen
funding:
  - https://www.buymeacoffee.com/dev_cetera
topics:
  - source-gen
  - build-runner
  - code-generation
  - screen
  - pages

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  df_collection: ^0.9.1
  df_config: ^0.6.2
  df_gen_core: ^0.6.5
  df_generate_dart_indexes: ^0.5.11
  df_generate_dart_models_core: ^0.9.7
  df_log: ^0.2.4
  df_screen_core: ^0.5.0
  df_string: ^0.2.4
  df_safer_dart: ^0.10.0
  df_type: ^0.10.3
  args: ^2.6.0
  path: ^1.9.1

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^5.1.0
  test: ^1.25.12
  

## -----------------------------------------------------------------------------

executables:
  gen-screen: gen_screen
  gen-screen-access: gen_screen_access
  gen-screen-bindings: gen_screen_bindings
